batch_type: numel
batch_bins: 4000000
accum_grad: 8
max_epoch: 20
patience: none
init: none
best_model_criterion:
-   - valid
    - cer_ctc
    - min
keep_nbest_models: 3

encoder: conformer_moe
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: [1024,1024,1024]
    macaron_style_linear_units: 1024
    num_blocks: 18
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31
    positionwise_layer_type: utt_mix_moe
    macaron_positionwise_layer_type: linear
    num_experts: 3
    capacity_factor: 1.0
    use_load_balancing_loss: true
    gs: true
    gs_mode: soft
    tau: 0.15

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.002
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

num_att_plot: 0

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5
